accounts/urls.py
from django.urls import path
from .views import *
from accounts.views import *


urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout_user/', logout_view, name='logout_user'),
    path('forgot_pass/', forgot_password, name='forgot_password'),
]

core/urls.py
from django.urls import path
from .views import (
    CategoryView,
    HomeView,
    about,
    contact,
    profile,
    NewVideo,
    VideoView,
    CommentView,
    VideoFileView,
    CreateChannelView,
    ChannelView
)
from core import views
from accounts.views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path('profile/<str:pk>', profile, name='profile'),
    path('video_category/<str:slug>', CategoryView, name='Video'),
    path('new_video', NewVideo.as_view()),
    path('video/<int:id>/<int:new>/', VideoView.as_view()),
    path('comment', CommentView.as_view()),
    path('get_video/<file_name>', VideoFileView.as_view()),
    path('createchannel', CreateChannelView.as_view()),
    path('<user>/channel', ChannelView.as_view()),
    path('video/<int:v_id>/<int:u_id>/like',
         views.video_like, name='video_like'),
    path('video/<int:v_id>/<int:u_id>/unlike',
         views.video_unlike, name='video_unlike'),
    path('video/<int:v_id>/<int:u_id>/dislike',
         views.video_dislike, name='video_dislike'),
    path('video/<int:v_id>/<int:u_id>/undislike',
         views.video_undislike, name='video_undislike'),
    path('liked/', views.liked_videos, name='liked_videos'),
    path('watch_history/', views.watch_history, name='watch_history'),
    path('trending/', views.trending, name='trending'),
    path('help/', views.help, name='help'),
    path('channel_subscribe/<int:c_id>/',
         views.channel_subscribe, name='channel_subscribe'),
    path('channel_unsubscribe/<int:c_id>/',
         views.channel_unsubscribe, name='channel_unsubscribe'),
    path('subscriptions/', views.subscriptions, name='subscriptions'),
    path('channels_list/', views.channels_list, name='channels_list'),
    # path('signup', signup, name='signup'),
    # path('signin', signin, name='signin'),
    # path('logout', logout, name='logout'),
    # path('register/', RegisterView.as_view(), name='register'),
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts.views import *
from django.views.generic import TemplateView, RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include("accounts.urls")),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
# from django.core.validators import FileExtensionValidator
from django.utils.text import slugify
from django.urls import reverse
import uuid
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyAccountManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
            is_staff=True
        )
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )

        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    firstname = models.CharField(max_length=100, blank=False)
    lastname = models.CharField(max_length=100, blank=False)
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(
        verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True


# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     id_user = models.IntegerField()
#     bio = models.TextField(blank=True)
#     location = models.CharField(max_length=100, blank=True)

#     def __str__(self):
#         return self.user.username

class Profile(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    id_user = models.IntegerField()
    bio = models.TextField(blank=True)
    profile_image = models.ImageField(
        upload_to='profile_images', default="https://dummyimage.com/99x24")
    location = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from accounts.models import Account


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        max_length=60, help_text='Required. Add a valid email address')

    class Meta:
        model = Account
        fields = ('firstname', 'lastname', 'username',
                  'email', 'password1', 'password2')


class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('username', 'password')

    def clean(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            password = self.cleaned_data['password']

            if not authenticate(username=username, password=password):
                raise forms.ValidationError("Invalid login")


class AccountUpdateForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('email', 'username')

    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            try:
                account = Account.objects.exclude(
                    pk=self.instance.pk).get(email=email)
            except Account.DoesNotExist:
                return email
            raise forms.ValidationError(
                'Email "%s" is already in use.' % email)

    def clean_username(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            try:
                account = Account.objects.exclude(
                    pk=self.instance.pk).get(username=username)
            except Account.DoesNotExist:
                return username
            raise forms.ValidationError(
                'Username "%s" is already in use.' % username)

accounts/views.py
from django.contrib.auth import authenticate, login, logout as logoutUser
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import render, redirect

from accounts.forms import AccountAuthenticationForm, AccountUpdateForm, RegistrationForm
from accounts.models import Account, Profile
# from django.utils.http import is_safe_url


def register(request):
    template_name = 'accounts/register.html'
    context = {}

    if request.POST:
        form = RegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(username=username, password=raw_password)
            # create a profile object for the new user
            user_model = Account.objects.get(username=username)
            new_profile = Profile.objects.create(
                user=user_model, id_user=user_model.id)
            new_profile.save()
            messages.success(request, 'User registered successfully.')
            return redirect('login')
        else:
            messages.error(request, 'Invalid form submission.')
            messages.error(request, form.errors)
            context = {"signupform": form}
    else:  # GET Request
        form = RegistrationForm()
        context = {"signupform": form}
    return render(request, template_name, context)


def login_view(request):
    template_name = 'accounts/login.html'
    form = AccountAuthenticationForm()

    user = request.user
    if user.is_authenticated:
        return redirect('/')
    if request.POST:
        form = AccountAuthenticationForm(request.POST or None)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, 'User Log in failed.')
        else:
            messages.error(
                request, 'Username or Password Incorrect, User Log in failed.')

    else:
        form = AccountAuthenticationForm()
    context = {"loginform": form}
    return render(request, template_name, context)


def forgot_password(request):
    return render(request, 'accounts/forgot_password.html')
# @login_required(login_url='accounts/login')
# def profile_view(request):
#     template_name='accounts/profile.html'
#     args = request.user
#     booking_history = Book.objects.filter(user=args)
#     context={
#         'booking_history':booking_history,
#     }
#     return render(request,template_name,context)
@login_required(login_url='account/login')
def logout_view(request):
    logoutUser(request)
    return redirect('/')


# def account_view(request):
#     template_name = 'accounts/update.html'
#     if not request.user.is_authenticated:
#         return redirect('login')

#     context = {}

#     if request.POST:
#         form = AccountUpdateForm(request.POST, instance=request.user)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Accout  Updated Successfully.')
#             return redirect('profile')
#         else:
#             messages.error(request, 'Invalid , Not Updated')
#             messages.error(request, form.errors)
#     else:
#         form = AccountUpdateForm(
#             initial={
#                 "email": request.user.email,
#                 "username": request.user.username,
#             }
#         )
#     context['account_form'] = form
#     return render(request, template_name, context)

accounts/templates/accounts/forgot_password.html
{% load static %}
{% load widget_tweaks %} 
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Forgor Password Page</title>
	<link rel="stylesheet" type="text/css" href="/static/assets/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="/static/assets/css/style.css">
</head>
<body>
	<div class="main">
		<div class="container-fluid">
			<div class=" pt-4">
				{% if messages %}
					  {% for message in messages %}
						<div class="alert {{message.tags}} alert-dismissible fade show" role="alert">
							<strong>{{ message|capfirst }}</strong>
						  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						  </button>
						</div>
					 {% endfor %}
					{% endif %}
				</div>
			
			<div class="row">
				<div class="col-sm-4"></div>
				<div class="col-sm-4 centered-form">
					<img src="/static/assets/img/splitunity.png" class="login-logo">
					<form action="" method="POST">
						{% csrf_token %}
                        <div>
                            Enter your email address and we'll send you a link you can use to pick a new password.
                        </div>
						<div class="login-form">
							<div class="form-group">
                                <input type="email" name="" placeholder="Email" class="form-control">
								<!-- <input type="email" name="" placeholder="Email" class="form-control"> -->
							</div>
							
							<div class="form-group">
								<button type="submit" class="btn">RESET PASSWORD</button>
							</div>
							<div class="form-group">
								<button class="btn"><a href="{% url 'login' %}" style="text-decoration: none; color:black;">LOGIN</a></button>
							</div>
						</div>
                        <input
                          type="hidden"
                          value="1"
                        />
					</form>
				</div>
				<div class="col-sm-4"></div>
				 
			</div> 
		</div>
		<!-- <div class="col-sm-12d">
				<div class="login-footer">
					<ul>
						<li>&copy; SplitUnity 2022</li>
						<li><a href="#">Terms of service</a></li>
						<li><a href="{% url 'core:about' %}">About</a></li>
						<li><a href="#">Privacy policy</a></li>
					</ul> 
				</div>
			</div> -->
	</div>
	<script type="text/javascript" src="/static/assets/js/jquery-3.6.3.min.js"></script>
	<script type="text/javascript" src="/static/assets/js/bootstrap.js"></script>
</body>
</html>

accounts/templates/accounts/login.html
{% load static %}
{% load widget_tweaks %} 
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Login Page</title>
	<link rel="stylesheet" type="text/css" href="/static/assets/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="/static/assets/css/style.css">
</head>
<body>
	<div class="main">
		<div class="container-fluid">
			<div class=" pt-4">
				{% if messages %}
					  {% for message in messages %}
						<div class="alert {{message.tags}} alert-dismissible fade show" role="alert">
							<strong>{{ message|capfirst }}</strong>
						  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						  </button>
						</div>
					 {% endfor %}
					{% endif %}
				</div>
			
			<div class="row">
				<div class="col-sm-4"></div>
				<div class="col-sm-4 centered-form">
					<img src="/static/assets/img/splitunity.png" class="login-logo">
					<div class="text-right no-account">Don't have an account? <a href="{% url 'register' %}">Register</a></div>
					<form action="" method="POST">
						{% csrf_token %}
						<div class="login-form">
							<div class="form-group">
								{{loginform.username|attr:"type:text"|attr:"placeholder:Your username"|add_class:"form-control"}}
								<!-- <input type="email" name="" placeholder="Email" class="form-control"> -->
							</div>
							<div class="form-group">
								{{loginform.password|attr:"type:password"|attr:"placeholder:Your Password"|add_class:"form-control"}}
								<!-- <input type="password" name="" placeholder="Password" class="form-control"> -->
							</div>
							<div class="form-group">
								<button type="submit" class="btn">LOGIN</button>
							</div>
							<div class="text-center no-account"><a href="{% url 'forgot_password' %}">Forgot password</a></div>
						</div>
						<input
                          type="hidden"
                          value="1"
                        />
					</form>
				</div>
				<div class="col-sm-4"></div>
				 
			</div> 
		</div>
		<!-- <div class="col-sm-12d">
				<div class="login-footer">
					<ul>
						<li>&copy; SplitUnity 2022</li>
						<li><a href="#">Terms of service</a></li>
						<li><a href="{% url 'core:about' %}">About</a></li>
						<li><a href="#">Privacy policy</a></li>
					</ul> 
				</div>
			</div> -->
	</div>
	<script type="text/javascript" src="/static/assets/js/jquery-3.6.3.min.js"></script>
	<script type="text/javascript" src="/static/assets/js/bootstrap.js"></script>
</body>
</html>

accounts/templates/accounts/register.html
{% load static %}
{% load widget_tweaks %} 
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Signup Page</title>
	<link rel="stylesheet" type="text/css" href="/static/assets/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="/static/assets/css/style.css">
	 {% load widget_tweaks %} 
</head>
<body>
	<div class="main">
		<div class="container-fluid">
			
			<div class=" pt-4">
				{% if messages %}
					  {% for message in messages %}
						<div class="alert {{message.tags}} alert-dismissible fade show" role="alert">
							<strong>{{ message|capfirst }}</strong>
						  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						  </button>
						</div>
					 {% endfor %}
					{% endif %}
				</div>
			<div class="row">
				<div class="col-sm-4"></div>
				<div class="col-sm-4 centered-form">
					<img src="/static/assets/img/splitunity.png" class="login-logo">
					<div class="text-right no-account">Already have an account? <a href="{% url 'login' %}">Login</a></div>
					<form action="" method="POST">
						{% csrf_token %}
						<div class="login-form">
							<div class="form-group">
								{{signupform.firstname|attr:"type:text"|attr:"placeholder:Your FirstName"|add_class:"form-control"}}
								<!-- <input type="email" name="" placeholder="Email" class="form-control"> -->
							</div>
							<span style="color:red; list-style-type:none;">{{signupform.firstname.errors}}</span>
							<div class="form-group">
								{{signupform.lastname|attr:"type:text"|attr:"placeholder:Your LastName"|add_class:"form-control"}}
								<!-- <input type="password" name="" placeholder="Password" class="form-control"> -->
							</div>
							<span style="color:red; list-style-type:none;">{{signupform.lastname.errors}}</span>
							<div class="form-group">
								{{signupform.username|attr:"type:text"|attr:"placeholder:Your username"|add_class:"form-control"}}
								<!-- <input type="password" name="" placeholder="Password" class="form-control"> -->
							</div>
							<span style="color:red; list-style-type:none;">{{signupform.username.errors}}</span>
							<div class="form-group">
								{{signupform.email|attr:"type:email"|attr:"placeholder:Your Email"|add_class:"form-control"}}
								<!-- <input type="password" name="" placeholder="Password" class="form-control"> -->
							</div>
							<span style="color:red; list-style-type:none;">{{signupform.email.errors}}</span>
							<div class="form-group">
								{{signupform.password1|attr:"type:password"|attr:"placeholder:Your Password"|add_class:"form-control"}}
								<!-- <input type="password" name="" placeholder="Password" class="form-control"> -->
							</div>
							<span style="color:red; list-style-type:none;">{{signupform.password1.errors}}</span>
							<div class="form-group">
								{{signupform.password2|attr:"type:password"|attr:"placeholder:Repeat Your Password"|add_class:"form-control"}}
								<!-- <input type="password" name="" placeholder="Password" class="form-control"> -->
							</div>
							<span style="color:red; list-style-type:none;">{{signupform.password2.errors}}</span>
							<div class="form-group">
								<button type="submit" class="btn">SIGNUP</button>
							</div>
							
						</div>
						<input
                          type="hidden"
                          value="1"
                        />
					</form>
				</div>
				<div class="col-sm-4"></div>
				 
			</div> 
		</div>
		<!-- <div class="col-sm-12d">
				<div class="login-footer">
					<ul>
						<li>&copy; SplitUnity 2022</li>
						<li><a href="#">Terms of service</a></li>
						<li><a href="{% url 'core:about' %}">About</a></li>
						<li><a href="#">Privacy policy</a></li>
					</ul> 
				</div>
			</div> -->
	</div>
	<script type="text/javascript" src="/static/assets/js/jquery-3.6.3.min.js"></script>
	<script type="text/javascript" src="/static/assets/js/bootstrap.js"></script>
</body>
</html>