core/urls.py
from django.urls import path
from .views import (
    CategoryView,
    HomeView,
    about,
    contact,
    profile,
    NewVideo,
    VideoView,
    CommentView,
    VideoFileView,
    CreateChannelView,
    ChannelView
)
from core import views
from accounts.views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path('profile/<str:pk>', profile, name='profile'),
    path('video_category/<str:slug>', CategoryView, name='Video'),
    path('new_video', NewVideo.as_view()),
    path('video/<int:id>/<int:new>/', VideoView.as_view()),
    path('comment', CommentView.as_view()),
    path('get_video/<file_name>', VideoFileView.as_view()),
    path('createchannel', CreateChannelView.as_view()),
    path('<user>/channel', ChannelView.as_view()),
    path('video/<int:v_id>/<int:u_id>/like',
         views.video_like, name='video_like'),
    path('video/<int:v_id>/<int:u_id>/unlike',
         views.video_unlike, name='video_unlike'),
    path('video/<int:v_id>/<int:u_id>/dislike',
         views.video_dislike, name='video_dislike'),
    path('video/<int:v_id>/<int:u_id>/undislike',
         views.video_undislike, name='video_undislike'),
    path('liked/', views.liked_videos, name='liked_videos'),
    path('watch_history/', views.watch_history, name='watch_history'),
    path('trending/', views.trending, name='trending'),
    path('help/', views.help, name='help'),
    path('channel_subscribe/<int:c_id>/',
         views.channel_subscribe, name='channel_subscribe'),
    path('channel_unsubscribe/<int:c_id>/',
         views.channel_unsubscribe, name='channel_unsubscribe'),
    path('subscriptions/', views.subscriptions, name='subscriptions'),
    path('channels_list/', views.channels_list, name='channels_list'),
    # path('signup', signup, name='signup'),
    # path('signin', signin, name='signin'),
    # path('logout', logout, name='logout'),
    # path('register/', RegisterView.as_view(), name='register'),
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts.views import *
from django.views.generic import TemplateView, RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include("accounts.urls")),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<!-- Open HTML -->
<html lang="en-US">
  <!-- Open Head -->
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <!-- /Added by HTTrack -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="profile" href="http://gmpg.org/xfn/11" />
    <script>
      document.documentElement.className =
        document.documentElement.className + ' yes-js js_active js';
    </script>
    <title>
      {% block title %}{% endblock title %} 
    </title>
    <meta name="robots" content="max-image-preview:large" />
    {% include "links.html" %}
  </head>

  <!-- Close Head -->
  <body
    class="bp-legacy page-template-default page page-id-776 theme-vidio pmpro-body-has-access woocommerce-no-js youzify-blue-scheme not-logged-in layout-wide wpb-js-composer js-comp-ver-6.7.0 vc_responsive no-js"
  >
    <!-- Display newsletter popup -->
    <!-- Open haru main -->
    <div id="haru-main">
      {% include "navbar.html" %}
      <!-- Open HARU Content Main -->
      {% include 'messages.html' %}
      {% block content %} {% endblock content %}
      <!-- Close HARU Content Main -->

      {% include "footer.html" %}
    </div>
    <!-- Close haru main -->
    <a class="back-to-top" href="javascript:;">
      <i class="fa fa-chevron-up"></i>
    </a>
    <div class="haru-ajax-overflow">
      <div class="haru-ajax-loading">
        <div class="loading-wrapper">
          <div class="spinner" id="spinner_one"></div>
          <div class="spinner" id="spinner_two"></div>
          <div class="spinner" id="spinner_three"></div>
          <div class="spinner" id="spinner_four"></div>
          <div class="spinner" id="spinner_five"></div>
          <div class="spinner" id="spinner_six"></div>
          <div class="spinner" id="spinner_seven"></div>
          <div class="spinner" id="spinner_eight"></div>
        </div>
      </div>
    </div>
    <div class="haru-lightbox-overlay"></div>
    <div class="haru-lightbox">
      <div class="close-lightbox"><i class="haru-icon haru-times"></i></div>
    </div>
    <!-- Memberships powered by Paid Memberships Pro v2.5.10.1.
 -->
    {% include 'scripts.html' %}
  </body>

  <!-- Mirrored from demo.harutheme.com/vidio/home-2/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 10 Dec 2022 08:54:50 GMT -->
</html>

templates/channel.html
{% extends 'base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}
{% load widget_tweaks %} 
{% block title %}SplitUnity | Channel{% endblock title %} 
{% block content %}


<div id="haru-content-main" class="clearfix">
    <div
      class="haru-page-title-section"
      style="
        background-image: url(/static/wp-content/themes/cr8iveshare/framework/admin-assets/images/theme-options/bg-page-title.jpg);
      "
    >
      <section class="haru-page-title-wrapper page-title-wrapper-bg">
        <div class="container">
          <div class="page-title-inner">
            <div class="block-center-inner">
              <h2>Create Channel!</h2>
            </div>
          </div>
        </div>
      </section>
      <div class="haru-breadcrumb-wrapper">
        <div class="container">
          <ul class="breadcrumbs">
            <li><a href="../index.html" class="home">Home</a></li>
            <li><span>Create Channel!</span></li>
          </ul>
        </div>
      </div>
    </div>
    <main class="haru-page">
      <div class="container clearfix">
        <div class="row clearfix">
          <div class="page-content col-md-12 col-sm-12 col-xs-12">
            <div class="page-wrapper">
              <div class="page-inner clearfix">
                <div
                  id="post-683"
                  class="post-683 page type-page status-publish hentry pmpro-has-access clearfix"
                >
                  <div class="entry-content">
                    <div class="youzify-membership-login-shortcode">
                      <div
                        class="youzify-membership-form youzify-membership-login-page form-with-header form-with-labels form-no-icons form-full-border form-border-flat"
                      >
                        <header class="youzify-membership-form-header">
                          <div
                            class="youzify-membership-form-cover youzify-membership-default-cover"
                            style="
                              background-image: url(/static/wp-content/plugins/youzer/includes/public/assets/images/geopattern.png);
                            "
                          >
                            <h2 class="form-cover-title">Create your channel</h2>
                          </div>
                        </header>
  
                        <form
                          id="youzify-membership-form"
                          class="youzify-membership-login-form"
                          method="POST"
                          action=""
                          enctype= 'multipart/form-data'
                        >
                          {% csrf_token %}
                          <!-- After Form Buttons -->
                          <!-- {{form}} -->
                          <!-- {% for error in profile_form.non_field_errors %}
                          <label>{{ error|escape }} </label>
                          {% endfor %} -->
                          <div class="youzify-membership-form-item">
                            <div class="youzify-membership-item-content">
                              <label for="user_login">Channel Name</label>
                              <div class="youzify-membership-field-content">
                                {{form.channel_name|attr:"type:text"|attr:"placeholder:Your channel name"}}
                              </div>
                            </div>
                          </div>
                          <div class="youzify-membership-form-item">
                            <div class="youzify-membership-item-content">
                              <label for="user_login">Channel Image</label>
                              <div class="youzify-membership-field-content">
                                {{form.channel_image|attr:"type:file"|attr:"placeholder:Your channel image"}}
                              </div>
                            </div>
                          </div>
                          <div
                            class="youzify-membership-form-actions form-fullwidth-button form-border-radius"
                          >
                            <div
                              class="youzify-membership-action-item youzify-membership-submit-item"
                            >
                              <div class="youzify-membership-item-inner">
                                <button
                                  type="submit"
                                  value="submit"
                                  name="signin_submit"
                                >
                                  <span class="youzify-membership-button-title"
                                    >Create</span
                                  >
                                </button>
                              </div>
                            </div>
                          </div>
                          
                          <!-- After Form Buttons -->
  
                          <input
                            type="hidden"
                            name="youzify-membership-form"
                            value="1"
                          />
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>

{% endblock content %}

templates/channels_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}SplitUnity | All Channels{% endblock title %} 
{% block content %}

<div id="haru-content-main" class="clearfix">
  <div class="haru-archive-breadcrumbs">
    <div class="haru-container">
      <ul
        class="haru-breadcrumb"
        itemscope
        itemtype="http://schema.org/BreadcrumbList"
      >
        <li
          itemprop="itemListElement"
          itemscope
          itemtype="http://schema.org/ListItem"
        >
          <a itemprop="item" href="{% url 'core:index' %}"
            ><span itemprop="name">Home</span></a
          ><meta itemprop="position" content="0" />
        </li>
        <span class="delimiter"> &raquo; </span>
        <li
          itemprop="itemListElement"
          itemscope
          itemtype="http://schema.org/ListItem"
        >
          <span itemprop="name" class="current">Channels</span
          ><meta itemprop="position" content="2" />
        </li>
      </ul>
      <!-- .breadcrumbs -->
    </div>
  </div>
  <div class="haru-archive-channel haru-container">
    <!-- Content -->
    <div class="archive-content has-right-sidebar">
      <div class="haru-archive-top">
        <div class="haru-archive-top-left">
          <h6 class="archive-channel__title">
            {% if channel_count < 0 %}
            No Channels
            {% elif channel_count == 1  %}
            Has total of
            <span class="archive-channel__total-count">{{channel_count}} channel</span>
            {% else %}
            Has total of
              <span class="archive-channel__total-count">{{channel_count}} channels</span>
            {% endif %}
            
          </h6>
        </div>
        <div class="haru-archive-top-right">
          <div class="haru-archive-layout-toggle">
            <a
              href="javascript:;"
              class="toggle-layout active"
              data-layout="grid"
              >Grid<i class="haru-icon haru-grid"></i
            ></a>
            <a href="javascript:;" class="toggle-layout" data-layout="list"
              >List<i class="haru-icon haru-list-small"></i
            ></a>
            <a href="javascript:;" class="toggle-layout" data-layout="list-2"
              >List 2<i class="haru-icon haru-list-small"></i
            ></a>
          </div>
          <div class="haru-archive-order">
            <div class="order-item-current">date</div>
            <ul class="order-items">
              <li class="order-item selected">
                <a
                  href="indexaccc.html?post_type=haru_channel&amp;paged=1&amp;orderby=date"
                  >Date</a
                >
              </li>
              <li class="order-item">
                <a
                  href="index2f29.html?post_type=haru_channel&amp;paged=1&amp;orderby=title"
                  >Title</a
                >
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div
        class="archive-channel-list layout-wrap style-grid grid-columns grid-columns__2"
      >
      {% if channels %}
        
      
      {% for channel in channels %}
        <article class="grid-item channel-item default">
          <div class="channel-item__thumbnail">
            <a href="sport-channel/index.html">
              <img
                width="1600"
                height="900"
                src="{{channel.channel_image.url}}"
                class="attachment-post-thumbnail size-post-thumbnail wp-post-image"
                alt=""
                loading="lazy"
                
                sizes="(max-width: 1600px) 100vw, 1600px"
              />
            </a>
            <div class="channel-item__icon">
              <a
                href="sport-channel/index.html"
                class="channel-player-direct"
              ></a>
            </div>

            <div class="channel-item__subscribe">
              {% if user.is_authenticated %}
                {% if subscribed == False %}
              <a
                href="{% url 'core:channel_subscribe' c_id=channel.id %}"
                class="channel-subscribe button-background button-background--small "
              >
                <span class="status-subscribe"
                  ><i class="haru-icon haru-user-plus"></i
                ></span>
               
                <span class="text-subscribe">Subscribe</span>
                <!-- <span class="count-subscribed">{{ channel.subscribers }}</span> -->
              </a>
              {% else %}
              <a
              href="{% url 'core:channel_unsubscribe' c_id=channel.id %}"
              class="channel-subscribe button-background button-background--small "
            >
              <span class="status-subscribe"
                ><i class="haru-icon haru-user-times"></i
              ></span>
              <span class="text-subscribe">UnSubscribe</span>
              <!-- <span class="count-subscribed">{{ channel.subscribers }}</span> -->
            </a>
            {% endif %}
            {% endif %}
            </div>
          </div>
          <div class="channel-item__content">
            <h6 class="channel-item__title">
              <a href="/{{ channel.user.username }}/channel">{{ channel.channel_name }}</a>
            </h6>
            <!-- <div class="channel-item__category">
              <a href="../channel-category/harutheme/index.html" rel="tag"
                >HaruTheme</a
              >
            </div> -->
            <div class="channel-item__meta">
              <div class="channel-item__author">
                <i class="fa fa-user"></i>
                <a href="/{{ channel.user.username }}/channel">{{ channel.user.username }}</a>
              </div>
              <div class="channel-item__date">
                <i class="fa fa-calendar"></i>January 14, 2020
              </div>
              <div class="channel-item__view">
                <div class="post-views-count">
                  <span class="post-views-label">views</span>
                  <i class="fa fa-eye"></i>
                  <span class="post-view-count">0</span>
                  <span class="post-view-unit"> view</span>
                </div>
              </div>
              <div class="channel-item__videos-count">
                10<span> videos</span>
              </div>
              <div class="channel-item__count-subscribed">
                <span class="count-subscribed">{{ channel.subscribers }}</span
                >
                {% if channel.subscribers == 1 %}
                <span class="count-subscribed-unit"> subscriber</span>
                {% else %}
                <span class="count-subscribed-unit"> subscribers</span>
                {% endif %}
                
              </div>
            </div>
          </div>
        </article>
        {% endfor %}
        {% else %}
        <h4>No Channels Created</h4>
        {% endif %}
      </div>

      <div class="archive-pagination">
        <nav
          id="infinite_scroll_button"
          data-max-page="2"
          data-msgText="Loading..."
          data-finishedMsg="All items loaded."
        >
          <a href="page/2/index.html"></a>
        </nav>
        <div
          id="infinite_scroll_loading"
          class="align-center infinite-scroll-loading"
        ></div>
      </div>
    </div>
    <!-- Sidebar -->
    <div class="archive-sidebar right-sidebar">
      <aside id="haru_widget_video_search-3" class="widget widget-video-search">
        <h4 class="widget-title"><span>Video search</span></h4>
        <form
          role="search"
          method="get"
          class="haru-video-search search-form default"
          action="https://demo.harutheme.com/vidio/"
        >
          <label for="haru-video-search-field-3">
            <span class="screen-reader-text">Search for:</span>
            <input
              type="search"
              id="haru-video-search-field-3"
              class="search-field"
              placeholder="Search videos&hellip;"
              value=""
              name="s"
            />
          </label>
          <button type="submit" class="search-submit" value="Search">
            <span>Search</span>
          </button>
          <input type="hidden" name="post_type" value="haru_video" />
        </form>
      </aside>
      <aside
        id="haru_widget_video_categories-3"
        class="widget widget-video-categories"
      >
        <h4 class="widget-title"><span>Video Categories</span></h4>
        <ul class="video-categories default">
          <li class="cat-item cat-item-61">
            <a href="../video-category/fashion/index.html">Fashion</a>
            <span class="count"><span class="list-count">10</span></span>
          </li>
          <li class="cat-item cat-item-60">
            <a href="../video-category/game/index.html">Game</a>
            <span class="count"><span class="list-count">10</span></span>
          </li>
          <li class="cat-item cat-item-33 cat-parent">
            <a href="../video-category/harutheme/index.html">HaruTheme</a>
            <span class="count"><span class="list-count">17</span></span>
          </li>
          <li class="cat-item cat-item-64">
            <a href="../video-category/sports/index.html">Sports</a>
            <span class="count"><span class="list-count">10</span></span>
          </li>
          <li class="cat-item cat-item-59">
            <a href="../video-category/technology/index.html">Technology</a>
            <span class="count"><span class="list-count">10</span></span>
          </li>
          <li class="cat-item cat-item-47">
            <a href="../video-category/travel/index.html">Travel</a>
            <span class="count"><span class="list-count">11</span></span>
          </li>
        </ul>
      </aside>
      <aside id="haru_widget_video_videos-5" class="widget widget-video-videos">
        <h4 class="widget-title"><span>Latest Videos</span></h4>
        <ul class="videos-list default">
          {% if most_recent_videos %}
            {% for video in most_recent_videos %}
          <li class="video-item clearfix">
            <div class="video-item__thumbnail">
              <a href="/video/{{ video.id }}/{{ 1 }}/"
                ><img
                  width="150"
                  height="150"
                  src="{% static 'wp-content/uploads/2019/11/fashion-19-150x150.jpg' %}"
                  class="attachment-thumbnail size-thumbnail wp-post-image"
                  alt=""
                  loading="lazy"
                  title="{{ video.title }}"
              /></a>
              <div class="video-item__duration">9:56</div>
            </div>
            <div class="video-item__content">
              <h6 class="video-item__title">
                <a
                  href="../video/haru-video-wordpress-theme/index.html"
                  title="{{ video.title }}"
                  >{{ video.title }}</a
                >
              </h6>
              <div class="video-item__meta">
                <div class="video-item__author">
                  <i class="fa fa-user"></i
                  ><a href="../members/admin/index.html">{{ video.user.username }}</a>
                </div>
                <div class="video-item__view">
                  <div class="post-views-count">
                    <span class="post-views-label">views</span>
                    <i class="fa fa-eye"></i>
                    <span class="post-view-count">{{ video.number_of_views }}</span>
                    <span class="post-view-unit"> views</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
          {% endfor %}
          {% else %}
          <p style="text-align: center;">No Videos for now</p>
          {% endif %}
        </ul>
      </aside>
      <aside id="haru_widget_video_tags-4" class="widget widget-video-tags">
        <h4 class="widget-title"><span>Video tags</span></h4>
        <div class="tagcloud default">
          <a
            href="../video-tag/filmmaker/index.html"
            class="tag-cloud-link tag-link-43 tag-link-position-1"
            style="font-size: 19.666666666667pt"
            aria-label="filmmaker (35 videos)"
            >filmmaker</a
          >
          <a
            href="../video-tag/movie/index.html"
            class="tag-cloud-link tag-link-44 tag-link-position-2"
            style="font-size: 15pt"
            aria-label="movie (34 videos)"
            >movie</a
          >
          <a
            href="../video-tag/theme/index.html"
            class="tag-cloud-link tag-link-42 tag-link-position-3"
            style="font-size: 22pt"
            aria-label="theme (36 videos)"
            >theme</a
          >
          <a
            href="../video-tag/video/index.html"
            class="tag-cloud-link tag-link-40 tag-link-position-4"
            style="font-size: 8pt"
            aria-label="video (31 videos)"
            >video</a
          >
          <a
            href="../video-tag/wordpress/index.html"
            class="tag-cloud-link tag-link-41 tag-link-position-5"
            style="font-size: 8pt"
            aria-label="wordpress (31 videos)"
            >wordpress</a
          >
        </div>
      </aside>
    </div>
  </div>
</div>

{% endblock content %}

templates/channelview.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %}SplitUnity | Channel{% endblock title %} 
{% block content %}

<div class="channelview">
    <h1>Welcome To {{ channel.channel_name }}</h1><br>
    <div>Author : {{ channel.user.username }}</div>

    <div align="right" style="margin-right:50px">
        {% if user.is_authenticated %}
            {% if subscribed == False %}
                <a href="{% url 'core:channel_subscribe' c_id=channel.id %}"><button class="button button5" style="background-color:red; width:150px"><b>Subscribe</b></button> </a>
            {% else %}
                <a href="{% url 'core:channel_unsubscribe' c_id=channel.id %}"><button class="button button5" style="background-color:grey; width:150px"><b>Unsubscribe</b></button> </a>
            {% endif %}
        {% endif %}
        <p style="margin-right:30px"><b>Subscribers : {{ channel.subscribers }}</b></p>
    </div>
    
</div>

<div class="video_area">
    <div class="ad_area">
        {% for video in videos %}
        <div class = "video_advertisement col-md-6">

            <div class="video_title">
                <h2 align="center" style="font-family: Courier New">{{ video.title }}</h2>
            </div>
            <div class="video_description">
                <h4 align="left">{{ video.description }}</h5>
                <h6 align="left, bottom" style="position: relative; float:bottom; margin-bottom:0px">Uploaded by {{ video.user }} on {{ video.datetime }}</h6>
                <h6 align = "left">{{ video.number_of_views }} views</h6>
            </div>
            <div class="watch_now">
                <a href="/video/{{ video.id }}/{{ 1 }}/"><button class="button button5">Watch Now!</button></a>	
            </div>
 
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

templates/messages.html
{% load static %}

<!-- Font Icon -->
<!-- Bootstrap css -->

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible {{message.tags}}">
      <button type="button" class="close" data-dismiss="alert">
      <i class="icon-close"></i>
      </button>
      <strong>{{message|capfirst}}</strong>
    </div>
 {% endfor %}
{% endif %}

<script src="{% static 'bootstrap.min.js' %}"></script>